### ISSUE TITLE
get java.lang.NoClassDefFoundError,Caused by: java.lang.ClassNotFoundException: org.jwat.gzip.GzipReader

### ISSUE THREAD

**Issue by flashkari** [lemurproject/nopol#1]
I download your code and import it to my eclipse (Mars) then I add all missing libraries.But, I got the following error when I run any of the command you mentioned in README.md. What should I do?

Exception in thread "main" java.lang.NoClassDefFoundError: org/jwat/gzip/GzipReader
    at org.jwat.warc.WarcReaderFactory.getReader(WarcReaderFactory.java:125)
    at lemur.nopol.ResponseIterator.<init>(ResponseIterator.java:61)
    at lemur.nopol.ProcessWarc.processFile(ProcessWarc.java:38)
    at lemur.nopol.ProcessWarc.main(ProcessWarc.java:119)
Caused by: java.lang.ClassNotFoundException: org.jwat.gzip.GzipReader
    at java.net.URLClassLoader.findClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 4 more

**Comment by flashkari** [comment]
I solve this problem.
